%% ================== GenerateOutputFiles2 ===============================
% this script generates the outputfiles stored under:
%
% ***
% 
% and produced for the study:
%
% Vandecrux, B., Fausto, R., van As, D., Langen, P. L., Sampson, K., 
% Steffen, K., Box, J. E. (2018). Heat budget of the Greenland firn.
% Manuscr. Prep. 1–17
%
% Contact: b.vandecrux@gmail.com
% ======================================================================
%%
clear all
close all
set(0,'defaultfigurepaperunits','centimeters');
   set(0,'DefaultAxesFontSize',16)
   set(0,'defaultfigurecolor','w');
set(0,'defaultfigureinverthardcopy','off');
set(0,'defaultfigurepaperorientation','portrait');
set(0,'defaultfigurepapersize',[29.7 25]);
set(0,'defaultfigurepaperposition',[.25 .25 [29.7 25]-0.5]);
set(0,'DefaultTextInterpreter','none');
set(0, 'DefaultFigureUnits', 'centimeters');
set(0, 'DefaultFigurePosition', [.25 .25 [29.7 25]-0.5]);
addpath(genpath('lib'))
addpath(genpath('Input'),genpath('Output'))
 
%% Weather data
% -           Date
% -          2m air temperature (recalculated using our own assumptions for roughness lengths and stability correction)
% -          2m relative humidity
% -          10m wind speed
% -          Precipitation rate
% -          SEB components (net shortwave radiation, downward longwave radiation from RACMO2.3p2, modelled upward longwave radiation, turbulent heat fluxes and subsurface heat flux)
% -          Modelled surface temperature
% -          Melt-water production


% loadng surface data
OutputFolder = uigetdir('./Output');
% extract run parameters
load(strcat(OutputFolder,'/run_param.mat'))
disp(c.station)

% extract surface variables
namefile = sprintf('%s/surf-bin-%i.nc',OutputFolder,1);
finfo = ncinfo(namefile);
names={finfo.Variables.Name};
for ii= 1:size(finfo.Variables,2)
    eval(sprintf('%s = ncread(''%s'',''%s'');', char(names{ii}), namefile,char(names{ii})));
end
time_mod = datenum(Year,1,Day,Hour,0,0);
if ~isfield(c,'verbose')
    c.verbose = 1;
end

    %% loading subsurface data
    % extracting observed
%             namefile = sprintf('%s/subsurf-bin-%i.nc',OutputFolder,1);
%     finfo = ncinfo(namefile);
%     names={finfo.Variables.Name};
%     for ii= 1:size(finfo.Variables,2)
%         eval(sprintf('%s = ncread(''%s'',''%s'');', char(names{ii}), namefile,char(names{ii})));
%     end
%     pore_space = snowc .* c.rho_water.*( 1./rho - 1/c.rho_ice);
%     excess_ice = max(0, snic * c.rho_water / c.rho_ice - pore_space);
%     thickness_act = snowc.*(c.rho_water./rho) + excess_ice;
%     
%     depth_act=zeros(size(thickness_act));
%     for j=1:length(thickness_act(1,:))
%             depth_act(1:end,j)=cumsum(thickness_act(1:end,j));
%     end
%       k_eff = 0.021 + 2.5e-6*rho.^2 ;        
%         GF_check =-(k_eff(1,:)) .* (T_ice(1,:)- T_ice(2,:)) ./ ( snic(1,:) + snowc(1,:));
    
% loading station data
    [time_yr, year, day, hour, pres,...
~, ~, ~, H_instr_temp, o_T1,o_T2, ...
~, ~, ~, H_instr_hum, o_RH1, o_RH2, ...
~, ~, ~, H_instr_wind, o_WS1, o_WS2,...
~, ~, ~, ~, T_ice_obs, ...
depth_thermistor, Surface_Height, Tsurf_obs, data_out, c] = ...
ExtractAWSData(c);

%% Surface variable
namefilesurf = [OutputFolder, '\',c.station,'_surface.nc'];
time = time-1;

% Changing origin coding from:
% 0: main station
% 1: CP2 at 6.5 km
% 2: Swiss Camp at 97 km
% 3: KAN_U at 67 km
% 4: RCM
% 5: MODIS
% 9: NOAA tower at 2 km
% 10: Miller's station at 2 km
%
% to:
% 0: main station
% 0<X<100: adjusted from secondary AWS located X km away from GC-Net station  
% 101: adjusted from RACMO2.3p2
% 102: calculated from SRin and nearest daily MODIS albedo (or MODIS albedo
% climatology if before 2000)

data_out.Snowfallmweq_origin = isnan(data_out.SurfaceHeightm)*101;
[data_out.AirTemperature2C_Origin] = ChangeOrigin(data_out.AirTemperature2C_Origin);
[data_out.RelativeHumidity2_Origin] = ChangeOrigin(data_out.RelativeHumidity2_Origin);
[data_out.WindSpeed2ms_Origin] = ChangeOrigin(data_out.WindSpeed2ms_Origin);
[data_out.ShortwaveRadiationDownWm2_Origin] = ChangeOrigin(data_out.ShortwaveRadiationDownWm2_Origin);
[data_out.ShortwaveRadiationUpWm2_Origin] = ChangeOrigin(data_out.ShortwaveRadiationUpWm2_Origin);
[data_out.Snowfallmweq_origin] = ChangeOrigin(data_out.Snowfallmweq_origin);

figure
    subplot(1,2,1)
    title(c.station)
    hold on
    plot(meltflux)
    SEB = GF + SRin-SRout+LRin-LRout_mdl+SHF+LHF;
    SEB(Tsurf<0)=0;
    SEB(SEB<0)=0;
    plot(SEB)
    axis tight square
    subplot(1,2,2)
    scatter(meltflux, SEB)
    hold on
    plot([min(SEB) max(SEB)],[min(SEB) max(SEB)],'k')
    axis tight square

    data = {time,...
        SRin, ...
            data_out.ShortwaveRadiationDownWm2_Origin,...
            SRout, ...
            data_out.ShortwaveRadiationUpWm2_Origin,...
            LRin, ...
            LRout_mdl, ...
           SHF,...
           LHF,...
           GF,...
           meltflux,...
           H_surf,...
           Surface_Height,...
           snowfall+sublimation_mweq,...
           meltflux*c.dt_obs/c.dev/c.L_fus/c.rho_water,...   
           sublimation_mweq,...
           snowfall,...
           data_out.Snowfallmweq_origin,...
           Tsurf+c.T_0,...
           snowbkt,...
           theta_2m,...
           data_out.AirTemperature2C_Origin,...
           RH_2m_wrtw,...
           data_out.RelativeHumidity2_Origin,...
           ws_10m,...
           data_out.WindSpeed2ms_Origin,...
           pres};

    varname =  {'time', 'SRin','SRin_origin','SRout','SRout_origin',...
        'LRin' 'LRout'...
        'SHF' 'LHF' 'GF' 'meltflux'...
        'H_surf_mod' 'H_surf_obs' 'SMB' 'melt' 'sublimation'...
        'snowfall' 'snowfall_origin'...
        'Tsurf' 'snowbkt',...
        'Ta_2m','Ta_2m_origin',...
        'RH_2m','RH_2m_origin',...
        'WS_10m','WS_10m_origin',...
        'Pres'};

    unit =  {'days since 1900-1-1 0:0:0' 'Wm-2' '-' 'Wm-2' '-' 'Wm-2' 'Wm-2' 'Wm-2' 'Wm-2' 'Wm-2' 'Wm-2' ...
        'm' 'm' 'm_weq' 'm_weq' 'm_weq' ...
        'm_weq', '-', 'K'  'm_weq','K', '-','%', '-','ms-1', '-','hPa'};


    long_var_names =  {'Time (UTC)',...
        'Incoming shortwave radiation' ...
        'Origin of SRin',...
        'Outgoing shortwave radiation' ...
        'Origin of SRout',...
        'Downward longwave radiation flux'...
        'Upward longwave radiation flux'...
        'Sensible heat flux' ...
        'Latent heat flux' ...
        'Conductive heat flux from subsurface' ...
        'Melt energy'...
        'Modelled surface height'...
        'Observed surface height'...
        'Surface mass balance' ...
        'Melt'...
        'Net sublimation'...
        'Snowfall' ...
        'Origin of snowfall estimate',...
        'Surface temperature', ...
        'Surface snow bucket',...
        '2m air temperature',...
        'Origin of Ta',...
        '2m relative humidity with regards to water',...
        'Origin of RH',...
        '10 m wind speed',...
        'Origin of WS',...
        'air pressure at the surface'};

     text_origin = ['0 = main station; '...
        '0<X<100 = adjusted from AWS located X km away; '...
        '101 = adjusted from RACMO2.3p2; '...
        '102 = calculated from SRin and nearest daily MODIS albedo '...
        '(or MODIS albedo climatology if before 2000)'];
%         
     comment = {'time stamp points at the beginning of each time interval',...
         '',....     SRin
        text_origin,...     SRin_origin
        '',....             SRout
        text_origin,...     SRout_origin
        'adjusted from RACMO2.3p2',...          LRin
        'Calculated by the SEB model.', ...     LRout
        'Calculated by the SEB model. Positive towards the surface.', ... SHF
        'Calculated by the SEB model. Positive towards the surface.', ... LHF
        'Calculated by the subsurface model. Positive towards the surface.', ... GF
        'Excess energy in the SEB available for melt',...meltflux
        'origin at the bottom of the model (~40 m w.e. deep)',...H_surf_mod
        'origin at the bottom of the station mast (~6 m deep)',...H_surf_obs
        'snowfall + net sublimation, or, snowfall - sublimation + deposition',...SMB
        '',...melt
        'sublimation if <0, deposition if>0',...sublimation
        'from increments in surface height and adjusted to snow pits',...snowfall
        '0 = from station; 101 = scaled from RACMO2.3p2',...snowfall_origin
        'Calculated from the modelled LRout using emissivity of 0.98', ...Tsurf
        'Fresh snow sitting on top of the firn model column. Added to the model when reaching 0.04 m w.e..',...snowbkt
        'Height standardized using the SEB model.', ...Ta_2m
        text_origin, ...Ta_2m_origin
        'With regards to water. Height standardized using the SEB model.',...RH_2m
        text_origin,...RH_2m_origin
        'Height standardized using the SEB model.',...WS_10m
        text_origin, ...WS_10m_origin
        '',...Pres
        };

     for ii=1:length(data)
             WriteNetCDF(namefilesurf,data{ii},...
                 'VariableName', varname{ii},...
                 'DimensionNames',{'time'},...
                 'Unit', unit{ii},...
                 'LongVariableName',long_var_names{ii},...
                 'Comment', comment{ii});
     end
      clear data varname unit comment long_var_names
      
    nccreate(namefilesurf,'latitude','Dimensions',{'lat' 1});
    ncwrite(namefilesurf,'latitude',c.lat);
    nccreate(namefilesurf,'longitude','Dimensions',{'longitude' 1});
    ncwrite(namefilesurf,'longitude',c.lon);
    nccreate(namefilesurf,'elevation','Dimensions',{'elevation' 1});
    ncwrite(namefilesurf,'elevation',c.elev_AWS);
    nccreate(namefilesurf,'timezone','Dimensions',{'timezone' 3},'DataType','char');
    ncwrite(namefilesurf,'timezone','UTC');

%% Subsurface variable
%         namefilesurf = ...
%             sprintf('./Output/Standard runs/%s_subsurface.nc',station2{i});
%         data = {data_AWS.time-datenum(1900,1,1,0,0,0),...
%             depth_act, rho, rho_avg', delta_rho_comp', ...
%             delta_rho_precip',...
%             delta_rho_subl', delta_rho_melt'};
%                 
%         varname =  {'time', 'depth', 'rho', 'rho_avg_20', 'delta_rho_comp',...
%         'delta_rho_precip','delta_rho_subl','delta_rho_melt'};
%         
%         unit =  {'days since 1900-1-1 0:0:0','m', 'kg/m3','kg/m3','kg/m3',...
%         'kg/m3','kg/m3','kg/m3'};
%         
%         long_var_names = {'Time (UTC)', 'Depth', 'Firn density', ...
%         'Average density of the top 20 m of firn',...
%         'density change in the top 20m due to compaction',...
%         'density change in the top 20m due to snowfall',...
%         'density change in the top 20m due to sublimation',...
%         'density change in the top 20m due to melt and refreezing',...
%         };
%      WriteNetCDF2(namefilesurf,[1:201]','VariableName', 'layers',...
%              'DimensionNames',{'layers'},...
%              'Unit', '',...
%              'LongVariableName','model layers');
%          for ii=1:length(data)
% 
%              if ismember(ii, 2:3)
%                  WriteNetCDF2(namefilesurf,data{ii},'VariableName', varname{ii},...
%                      'DimensionNames',{'layers','time'},...
%                      'Unit', unit{ii},...
%                      'LongVariableName',long_var_names{ii});
%              else
%                  WriteNetCDF2(namefilesurf,data{ii},'VariableName', varname{ii},...
%                      'DimensionNames',{'time'},...
%                      'Unit', unit{ii},...
%                      'LongVariableName',long_var_names{ii});
%              end
%          end
%           clear data varname unit long_var_names
           
